### ISSUE TITLE
Running benchmark for all tests?

### ISSUE THREAD

**Issue by reece** [ionelmc/pytest-benchmark#118]
I'd like to benchmark all tests. As far as I can tell from the docs, running benchmark requires writing a wrapper using the provided fixture. Is there a simpler way?

Ideally, I'd be able to provide a regexp of tests to benchmark and/or a simple decorator to wrap classes for me.

**Comment by ionelmc** [comment]
This is currently not supported. We could have a `--benchmark-all-tests-and-hope-there-no-side-effects` but then you see that using it would imply:
 
- each of your tests will be run many times to calibrate mesurement
- tests setup and other side-effects will skew measurements and perhaps even create wrong results

That's why the api is currently explicit and in "opt-in" style. 

What is your usecase anyway? Isn't pytest's `--durations` option enough for you? https://docs.pytest.org/en/latest/usage.html?highlight=durations#profiling-test-execution-duration

**Comment by reece** [comment]
Easy part first: I simply didn't know about --durations. Somebody else set me straight and that does indeed address my immediate goal.

Ideally, I'd have a way to compare test timings across a variety of environments and even set failures when they are outside of

**Comment by reece** [comment]
Easy part first: I simply didn't know about --durations. Somebody else set me straight and that does indeed address my immediate goal. Thanks.
