### ISSUE TITLE
Instructions on how to work with the results?

### ISSUE THREAD

**Issue by Nachtfeuer** [ionelmc/pytest-benchmark#159]
Hi,

About the link: https://travis-ci.org/Nachtfeuer/engine/jobs/644884454

Nice how the bechmarking is displaying the measurements and I can - of course - understand
if a method or function takes seconds, milli seconds, micro seconds or nano seconds to have an idea whether it's slow or fast.

I see now a few green, a few white and a few red colors but it doesn't tell me whether it's bad.
Even more it doesn't tell me whether the performance is faster or slower than in the last build.

Any helpful comments on what I should do in that direction?

Kind Regards,
Thomas

**Comment by ionelmc** [comment]
Hey, What you have there is a comparison of all the benchmarks you have, which obviously isn't very useful. A proper setup would use grouping features to compare your implementation to past runs or a reference implementation.

To compare against a past run you could use something like `--benchmark-autosave --benchmark-compare --benchmark-group-by=name`. I wouldn't do that on travis since the the performance you get from their vms won't be consistent. Try it on your local machine with turboboost disabled and cpu-sapping processes like your browser terminated. 

To compare against a reference implementation try something like this: https://github.com/ionelmc/python-lazy-object-proxy/blob/master/tests/test_lazy_object_proxy.py#L1834-L1839

Also, see: https://pytest-benchmark.readthedocs.io/en/stable/comparing.html

**Comment by Nachtfeuer** [comment]
Thanks
