### ISSUE TITLE
please give a complete example?

### ISSUE THREAD

**Issue by wumpus** [ionelmc/pytest-benchmark#56]
I'm unfamiliar with "py.test" or what a "fixture" is. Reading your docs, there is no complete example of a source file with appropriate command-line. Also, there didn't seem to be any pointers from your documentation to some docs about py.test that might explain. Sure, I can use google to find the info, but maybe it could be more obvious?

(and heck, googling didn't help! I see I'm supposed to run it under py.test, so that's why there's no import in the file... but... ? ... ok a few minutes of experiment, I eventually got it.)

**Comment by ionelmc** [comment]
I will fix this but I some need pointers as to what would be a good introductory material. Would this be a good start http://docs.pytest.org/en/latest/example/simple.html?highlight=fixtures? Something else?

**Comment by ionelmc** [comment]
Also, can you give some examples of what did you try to google and did not help?

**Comment by wumpus** [comment]
I was goggling for [pytest benchmark example] and the other places also weren't including the command-line, which turns out to be the secret ingredient. What I *thought* was missing from your example was an import line that would define benchmark(). It was a surprise that pytest automagically figures out what to do. (If I knew how pytest worked, I would not have been confused.)

I think that simply adding an appropriate command line to your existing examples would do. And your screenshots -- notice that the command line is cut off at the top!

pytest ./benchmarkme.py --benchmark-compare

**Comment by tjanson** [comment]
It took me a bit to figure it out, too. What I've gathered so far (by all means correct me if anything is wrong!):

* Define a function with *exactly* the name/signature `test_my_stuff(benchmark)`, which calls `benchmark(<function_to_be_benchmarked>)`.
* `benchmark` may only be called once. If you have several different functions you want to benchmark, I guess you need a separate script for each.
* Optionally, you may include setup and teardown code before/after that call. Alternatively (or: “equivalently”?) you can use `benchmark.pedantic(…, setup=…)`.
* That’s it. Aside from defining that function, there is nothing else to be done (e.g., no imports, no need to call anything).
* Run in shell: `$ py.test <name_of_script>`.

This may seem extremely obvious, but none if this was clear from the documentation to me. (Maybe that’s because I’m clueless, but nevertheless it would be nice to point this stuff out.)

**Comment by ionelmc** [comment]
I've added a "prologue" in the readme. Let me know if it addresses the confusing parts.

**Comment by wumpus** [comment]
Thank you, that looks great.
